import { ChevronDown, Menu } from "lucide-react";
import { useState } from "react";
import { Link, NavLink } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { CONTACT_EMAIL, orderedServices } from "@/lib/site";

const logoUrl = "https://customer-assets-wrfwihn1.emergentagent.net/job_khushboo-services/artifacts/60370bb24cb213f1_Arcturus%20White%20Logo.jpg";
const navLinkClass = ({ isActive }: { isActive: boolean }) => `relative whitespace-nowrap py-2 text-xs font-semibold transition-colors duration-200 after:absolute after:inset-x-0 after:-bottom-0.5 after:h-px after:origin-left after:bg-[#4263aa] after:transition-transform after:duration-200 ${isActive ? "text-[#0f2942] after:scale-x-100" : "text-[#475569] after:scale-x-0 hover:text-[#0f2942] hover:after:scale-x-100"}`;

export default function SiteHeader() {
  const [open, setOpen] = useState(false);
  return <header className="site-header sticky top-0 z-50 backdrop-blur-xl" data-testid="site-header"><div className="site-header-inner mx-auto flex h-[80px] max-w-7xl items-center justify-between px-5 sm:px-8 lg:px-10">
    <Link to="/" className="group flex items-center gap-3" data-testid="nav-logo-link"><span className="grid size-14 place-items-center overflow-hidden rounded-xl border border-[#e2dfd8] bg-white shadow-[0_10px_24px_-18px_rgba(15,41,66,0.55)] transition-transform duration-200 group-hover:-translate-y-0.5"><img src={logoUrl} alt="Arcturus Professional Services black logo" width="56" height="56" fetchPriority="high" decoding="async" className="size-full object-contain" data-testid="nav-logo-image" /></span><span className="hidden flex-col leading-none sm:flex" data-testid="nav-brand-name"><span className="font-hemicube text-sm tracking-[0.12em] text-[#0f2942]">ARCTURUS</span><span className="mt-1 text-[10px] text-[#64748b]">Professional Services</span></span></Link>
    <nav className="site-desktop-nav hidden items-center gap-6 md:flex" aria-label="Primary navigation" data-testid="desktop-navigation">
      <NavLink to="/" className={navLinkClass} data-testid="nav-link-home">Home</NavLink>
      <div className="group relative" data-testid="services-dropdown"><div className="flex items-center gap-1"><NavLink to="/services" className={navLinkClass} data-testid="nav-link-services">Services</NavLink><ChevronDown className="size-3 text-[#64748b] transition-transform duration-200 group-hover:rotate-180" /></div><div className="services-menu-panel invisible absolute left-1/2 top-full w-80 -translate-x-1/2 pt-4 opacity-0 transition-[opacity,visibility] duration-200 group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"><div className="premium-panel rounded-2xl border border-[#e2dfd8] bg-white p-2">{orderedServices.map((service) => <Link key={service.slug} to={`/services/${service.slug}`} className="flex items-center justify-between rounded-xl px-4 py-3 text-sm text-[#475569] transition-[background-color,color,transform] duration-200 hover:translate-x-0.5 hover:bg-[#eef2ff] hover:text-[#0f2942]" data-testid={`nav-service-${service.slug}`}><span>{service.title}</span><span className="font-mono text-[9px] text-[#4263aa]">{service.price}</span></Link>)}</div></div></div>
      <NavLink to="/about" className={navLinkClass} data-testid="nav-link-about">About</NavLink><NavLink to="/how-i-work" className={navLinkClass} data-testid="nav-link-how-i-work">How I Work</NavLink><NavLink to="/contact" className={navLinkClass} data-testid="nav-link-contact">Contact</NavLink>
    </nav>
    <Link to="/contact" className="site-contact-button hidden h-10 items-center rounded-full px-5 text-xs font-semibold text-white transition-[transform,box-shadow] duration-200 lg:inline-flex" data-testid="header-contact-button">Written enquiry</Link>
    <Sheet open={open} onOpenChange={setOpen}><SheetTrigger render={<Button variant="outline" size="icon" className="size-10 border-[#e2dfd8] md:hidden" />} data-testid="mobile-menu-button" aria-label="Open navigation"><Menu className="size-5" /></SheetTrigger><SheetContent side="right" className="w-[min(90vw,390px)] overflow-y-auto border-l-[#e2dfd8] bg-[#faf9f6] px-6"><SheetHeader className="border-b border-[#e2dfd8] pb-5 text-left"><SheetTitle className="font-serif text-2xl text-[#0f172a]" data-testid="mobile-menu-title">Arcturus</SheetTitle><p className="text-[11px] text-[#64748b]" data-testid="mobile-menu-email">{CONTACT_EMAIL}</p></SheetHeader><nav className="mt-6 flex flex-col" aria-label="Mobile navigation" data-testid="mobile-navigation"><NavLink to="/" onClick={() => setOpen(false)} className="border-b border-[#e2dfd8] py-3 font-serif text-xl text-[#0f2942]" data-testid="mobile-nav-link-home">Home</NavLink><Link to="/services" onClick={() => setOpen(false)} className="py-3 font-serif text-xl text-[#0f2942]" data-testid="mobile-nav-link-services">Services</Link><div className="mb-2 grid gap-1 border-b border-[#e2dfd8] pb-3 pl-3">{orderedServices.map((service) => <Link key={service.slug} to={`/services/${service.slug}`} onClick={() => setOpen(false)} className="py-2 text-sm text-[#64748b]" data-testid={`mobile-nav-service-${service.slug}`}>{service.title}</Link>)}</div><NavLink to="/about" onClick={() => setOpen(false)} className="border-b border-[#e2dfd8] py-3 font-serif text-xl text-[#0f2942]" data-testid="mobile-nav-link-about">About</NavLink><NavLink to="/how-i-work" onClick={() => setOpen(false)} className="border-b border-[#e2dfd8] py-3 font-serif text-xl text-[#0f2942]" data-testid="mobile-nav-link-how-i-work">How I Work</NavLink><NavLink to="/contact" onClick={() => setOpen(false)} className="border-b border-[#e2dfd8] py-3 font-serif text-xl text-[#0f2942]" data-testid="mobile-nav-link-contact">Contact</NavLink></nav><Link to="/contact" onClick={() => setOpen(false)} className="mt-7 inline-flex h-12 w-full items-center justify-center rounded-md bg-[#0f2942] text-sm font-semibold text-white" data-testid="mobile-contact-button">Send a written enquiry</Link></SheetContent></Sheet>
  </div></header>;
}
