import { ArrowUpRight, Check, FileText, LockKeyhole, Sparkles, X } from "lucide-react";
import { Link } from "react-router-dom";
import PageFrame from "@/components/PageFrame";
import Seo from "@/components/Seo";
import { orderedServices } from "@/lib/site";

export default function About() {
  return <PageFrame><Seo path="/about" />
    <section className="relative overflow-hidden border-b border-[#ddd8cd]" data-testid="about-hero"><div className="absolute right-[-7rem] top-12 size-80 rounded-full border border-[#4263aa]/20" aria-hidden="true" /><div className="mx-auto grid max-w-7xl gap-12 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1.18fr_0.82fr] lg:items-end lg:gap-20 lg:px-10 lg:py-28"><div className="relative z-10 min-w-0"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#4263aa]" data-testid="about-eyebrow">Independent, direct, documented</p><h1 className="mt-5 break-words font-serif text-[2.4rem] leading-[1.08] text-[#0f172a] sm:text-6xl lg:text-7xl" data-testid="about-heading">About Khushboo Tomar, B2B outreach freelancer</h1><div className="mt-8 max-w-3xl space-y-5 text-lg leading-8 text-[#475569]" data-testid="about-intro"><p>I&apos;m Khushboo Tomar, an independent freelancer based in New Delhi. I run LinkedIn management, B2B email outreach and lead generation for businesses in Ireland, the UK and across Europe.</p><p>I work alone, so you always deal with the person doing the work. No account managers, no hand-offs, no outsourcing of core tasks.</p></div></div><div className="relative z-10 rounded-t-[8rem] rounded-b-[2rem] bg-[#0f2942] p-7 text-white shadow-[0_30px_75px_-42px_rgba(15,41,66,0.78)]" data-testid="about-personal-panel"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#9bc8c0]">One point of contact</p><p className="mt-5 font-serif text-3xl leading-tight text-white">The person you brief is the person who does the work.</p></div></div></section>

    <section className="mx-auto max-w-7xl px-5 py-14 sm:px-8 lg:px-10" data-testid="about-facts">
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-2xl border border-[#ddd8cd] bg-[#fbf8f1] p-5">
          <p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#4263aa]">Based in</p>
          <p className="mt-3 font-serif text-2xl text-[#0f2942]">New Delhi, India</p>
        </div>
        <div className="rounded-2xl border border-[#ddd8cd] bg-[#fbf8f1] p-5">
          <p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#4263aa]">Markets</p>
          <p className="mt-3 font-serif text-2xl text-[#0f2942]">UK · Ireland · Europe</p>
        </div>
        <div className="rounded-2xl border border-[#ddd8cd] bg-[#fbf8f1] p-5">
          <p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#4263aa]">Work model</p>
          <p className="mt-3 font-serif text-2xl text-[#0f2942]">Independent freelancer</p>
        </div>
        <div className="rounded-2xl border border-[#ddd8cd] bg-[#fbf8f1] p-5">
          <p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#4263aa]">Communication</p>
          <p className="mt-3 font-serif text-2xl text-[#0f2942]">Written · Direct · Personal</p>
        </div>
      </div>
    </section>

    <section className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[0.78fr_1.22fr] lg:gap-24 lg:px-10" data-testid="about-background-section"><div className="relative min-h-[420px] overflow-hidden rounded-t-[7rem] rounded-b-[2rem] bg-[#2d2238] shadow-[0_25px_60px_-38px_rgba(45,34,56,0.72)]" data-testid="about-founder-image"><div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_20%,rgba(205,187,153,0.45),transparent_24%),linear-gradient(145deg,#2d2238,#6a556f_52%,#d9c4c4)]" /><div className="absolute -right-16 top-12 size-72 rounded-full border border-white/25" /><div className="absolute -right-2 top-28 size-56 rounded-full border border-white/15" /><div className="absolute left-8 top-10 text-[9px] font-extrabold uppercase tracking-[0.25em] text-white/65">ARCTURUS / 2014 → NOW</div><div className="absolute left-7 bottom-24 text-[15rem] font-bold leading-none tracking-[-0.08em] text-white/80">K</div><div className="absolute inset-x-0 bottom-0 bg-black/25 p-7 backdrop-blur-md"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#d7c39b]">Experience since 2014</p><p className="mt-2 text-sm text-white/72">B2B outreach, lead research, sales support and email deliverability</p></div></div><div className="self-center"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#765b9a]">Experience</p><h2 className="mt-4 font-serif text-4xl leading-tight text-[#0f172a] sm:text-5xl" data-testid="about-background-heading">My background</h2><p className="mt-7 text-base leading-8 text-[#475569]" data-testid="about-background-copy">I started my career in 2014 in email marketing and have spent over twelve years in B2B outreach, lead research, sales support and email deliverability. I&apos;ve worked closely with UK businesses, including recruitment firms, sales consultancies and financial services companies.</p><div className="mt-9 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#ece8f4] p-5"><p className="font-highlight text-3xl text-[#0f2942]">12+</p><p className="mt-2 text-xs leading-5 text-[#64748b]">years of focused B2B experience</p></div><div className="rounded-2xl bg-[#dcebe8] p-5"><p className="font-highlight text-3xl text-[#0f2942]">2014</p><p className="mt-2 text-xs leading-5 text-[#64748b]">the year I started in email marketing</p></div></div></div></section>

    <section className="bg-[#f1eee6]" data-testid="about-services-section"><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-24 lg:px-10"><div className="grid gap-10 lg:grid-cols-[0.58fr_1fr] lg:gap-20"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#4263aa]">Specialist support</p><h2 className="mt-4 font-serif text-4xl text-[#0f172a] sm:text-5xl" data-testid="about-services-heading">What I do</h2><p className="mt-6 max-w-sm text-base leading-7 text-[#64748b]">Six clearly priced services, each handled directly and documented in writing.</p></div><div className="grid gap-3 sm:grid-cols-2">{orderedServices.map((service, index) => <Link key={service.slug} to={`/services/${service.slug}`} className="premium-panel premium-lift rounded-2xl border border-[#ddd8cd] bg-[#fbf8f1] p-5" data-testid={`about-service-${service.slug}`}><div className="flex items-center justify-between gap-4"><span className="font-mono text-[9px] text-[#4263aa]">0{index + 1}</span><ArrowUpRight className="size-4 text-[#64748b]" /></div><h3 className="mt-5 font-serif text-xl text-[#0f2942]">{service.title}</h3><p className="mt-2 text-sm leading-6 text-[#64748b]">{["Profile, posting, outreach and nurture", "Setup, warm-up, campaigns and reporting", "Research, content, website support and admin", "Verified B2B contacts for your target market", "Branded short videos and reels", "Domain and DNS setup for better deliverability"][index]}</p></Link>)}</div></div></div></section>

    <section className="mx-auto grid max-w-7xl gap-6 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-2 lg:px-10" data-testid="about-work-compliance"><article className="rounded-[2rem] border border-[#d7dee9] bg-[#eef2ff] p-7 sm:p-10"><FileText className="size-7 text-[#4263aa]" /><h2 className="mt-6 font-serif text-4xl text-[#0f172a]" data-testid="about-work-heading">How I work</h2><p className="mt-6 text-base leading-8 text-[#475569]">Everything runs in writing, over WhatsApp, email or LinkedIn. I don&apos;t take calls. This keeps every decision, report and instruction documented, so nothing gets lost or misunderstood. You get clear written updates and regular reporting.</p><p className="mt-5 text-base leading-8 text-[#475569]">Payment is 100% upfront for the month, and my pricing is flat and published on each service page.</p></article><article className="rounded-[2rem] border border-[#c9ddd8] bg-[#e8f2ef] p-7 sm:p-10"><LockKeyhole className="size-7 text-[#2c7a73]" /><h2 className="mt-6 font-serif text-4xl text-[#0f172a]" data-testid="about-compliance-heading">How I handle data and compliance</h2><p className="mt-6 text-base leading-8 text-[#475569]">I use a B2B-only, GDPR and PECR-aware approach. I work with business-professional data, handle unsubscribe requests properly, and keep your data confidential. You always keep control of your own accounts and settings. This is not legal advice, and each client remains responsible for confirming the lawful basis and requirements that apply to their activity.</p></article></section>

    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:px-10" data-testid="about-proof-section">
      <div className="premium-proof-card">
        <div>
          <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#765b9a]">Client proof</p>
          <h2 className="mt-4 font-serif text-4xl text-[#0f172a] sm:text-5xl">Real recommendations. No made-up testimonials.</h2>
        </div>
        <div className="premium-proof-copy">
          <p>LinkedIn recommendations are available as genuine client feedback on my professional profile.</p>
          <a href="https://www.linkedin.com/in/khushboo-tomar" target="_blank" rel="noreferrer" className="luxury-inline-link">View LinkedIn profile <ArrowUpRight className="size-4" /></a>
        </div>
      </div>
    </section>

    <section className="bg-[#0f2942] text-white" data-testid="about-boundaries-tools"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 sm:py-24 lg:grid-cols-2 lg:gap-20 lg:px-10"><article><X className="size-7 text-[#b8a9d4]" /><h2 className="mt-6 font-serif text-4xl text-white" data-testid="about-boundaries-heading">What I don&apos;t do</h2><p className="mt-6 text-base leading-8 text-[#cbd5e1]">I don&apos;t offer graphic design, project or calendar management, or YouTube SEO. I&apos;d rather do a few things well than say yes to everything.</p></article><article><Sparkles className="size-7 text-[#9bc8c0]" /><h2 className="mt-6 font-serif text-4xl text-white" data-testid="about-tools-heading">Built with modern tools</h2><p className="mt-6 text-base leading-8 text-[#cbd5e1]">I use AI tools to work faster on research, writing and video, and I build and launch websites with AI platforms such as Emergent. This site is an example.</p></article></div></section>

    <section className="mx-5 my-20 rounded-[2rem] border border-[#d7dee9] bg-white px-6 py-12 shadow-[0_28px_65px_-44px_rgba(15,41,66,0.62)] sm:mx-8 sm:my-28 sm:px-10 lg:mx-auto lg:max-w-7xl lg:px-14" data-testid="about-contact-section"><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><Check className="size-6 text-[#2c7a73]" /><h2 className="mt-5 max-w-3xl font-serif text-4xl leading-tight text-[#0f172a] sm:text-5xl" data-testid="about-contact-heading">Send me a short written brief and I&apos;ll reply by email or WhatsApp.</h2></div><Link to="/contact" className="inline-flex h-12 shrink-0 items-center justify-center gap-2 rounded-md bg-[#0f2942] px-6 text-sm font-semibold text-white transition-[background-color,transform,box-shadow] duration-200 hover:-translate-y-0.5 hover:bg-[#243f5c] hover:shadow-lg" data-testid="about-contact-button">Contact me <ArrowUpRight className="size-4" /></Link></div></section>
  </PageFrame>;
}
