import { ArrowUpRight, Clock3, Mail, MapPin } from "lucide-react";
import PageFrame from "@/components/PageFrame";
import Seo from "@/components/Seo";
import ServiceFitGuide from "@/components/ServiceFitGuide";
import { Button } from "@/components/ui/button";
import { CONTACT_EMAIL, getContactHref } from "@/lib/site";

export default function Contact() {
  return (
    <PageFrame>
      <Seo path="/contact" title="Contact Khushboo | Arcturus Professional Services" description="Get in touch directly with Khushboo at Arcturus for tailored service enquiries, proposal scopes, and availability." />
      <section className="border-b border-[#e2dfd8]" data-testid="contact-hero"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24 lg:px-10 lg:py-28"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-[#92400e]" data-testid="contact-eyebrow">Start a conversation</p><h1 className="mt-5 max-w-4xl font-serif text-5xl font-medium leading-[1.06] tracking-[-0.035em] text-[#0f172a] sm:text-6xl lg:text-7xl" data-testid="contact-heading">A good enquiry does not need to be <span className="italic text-[#0f2942]">perfect.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#475569]" data-testid="contact-intro">Share what you are trying to move forward, which service feels relevant, and the timing you have in mind. Khushboo will reply with the next useful question or a clear way to scope the work.</p></div></section>
      <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20 lg:px-10" data-testid="contact-fit-section"><ServiceFitGuide /></section>
      <section className="mx-auto grid max-w-7xl gap-14 px-5 pb-20 sm:px-8 sm:pb-28 lg:grid-cols-[0.85fr_1.15fr] lg:gap-24 lg:px-10" data-testid="contact-details-section"><div className="rounded-xl bg-[#0f2942] p-7 text-white sm:p-10"><Mail className="size-8 text-[#f5d783]" /><p className="mt-8 font-mono text-[10px] uppercase tracking-[0.18em] text-[#f5d783]" data-testid="contact-direct-label">Direct email</p><a href={getContactHref()} className="mt-3 block break-all font-serif text-2xl leading-tight text-white transition-colors duration-200 hover:text-[#f5d783] sm:text-3xl" data-testid="contact-email-link">{CONTACT_EMAIL}</a><p className="mt-6 text-sm leading-6 text-[#b9c5d4]" data-testid="contact-email-note">Your email client will open with a simple prompt so you can include the context that helps most.</p><Button render={<a href={getContactHref()} />} className="mt-9 h-12 bg-white px-5 text-[#0f2942] hover:bg-[#f5d783]" data-testid="contact-email-button">Open email draft <ArrowUpRight className="ml-2 size-4" /></Button></div><div><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-[#92400e]" data-testid="contact-brief-label">What to include</p><h2 className="mt-4 max-w-lg font-serif text-4xl font-medium leading-tight text-[#0f172a] sm:text-5xl" data-testid="contact-brief-heading">Give the first reply somewhere useful to start.</h2><div className="mt-10 divide-y divide-[#e2dfd8] border-y border-[#e2dfd8]">{[["01", "Your business", "A line or two about what you do and who you serve."], ["02", "The need", "Which service you are considering, or what you need help moving forward."], ["03", "The timing", "Any launch date, recurring rhythm, or deadline that matters."], ["04", "The context", "Anything you have already tried, prepared, or decided."]].map(([number, title, copy]) => <div key={number} className="grid gap-3 py-6 sm:grid-cols-[48px_160px_1fr] sm:items-start sm:gap-6" data-testid={`contact-prompt-${number}`}><span className="font-mono text-[10px] text-[#c59b27]" data-testid={`contact-prompt-number-${number}`}>{number}</span><h3 className="font-serif text-xl text-[#0f2942]" data-testid={`contact-prompt-title-${number}`}>{title}</h3><p className="text-sm leading-6 text-[#64748b]" data-testid={`contact-prompt-copy-${number}`}>{copy}</p></div>)}</div></div></section>
      <section className="bg-[#f3f1ec]" data-testid="contact-expectations-section"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-24 lg:grid-cols-[0.7fr_1.3fr] lg:gap-20 lg:px-10"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#92400e]" data-testid="contact-expectations-eyebrow">Working expectations</p><h2 className="mt-4 max-w-sm font-serif text-4xl font-medium leading-tight text-[#0f172a] sm:text-5xl" data-testid="contact-expectations-heading">Direct, written, and clear.</h2></div><div className="grid gap-0 divide-y divide-[#d8d3c8] border-y border-[#d8d3c8]"><div className="flex gap-5 py-7"><Clock3 className="mt-1 size-5 shrink-0 text-[#c59b27]" /><div><h3 className="font-serif text-2xl text-[#0f2942]" data-testid="contact-expectation-response-title">A considered reply</h3><p className="mt-2 text-sm leading-6 text-[#64748b]" data-testid="contact-expectation-response-copy">Response timing depends on availability and the detail of the brief. The next step will be stated clearly in writing.</p></div></div><div className="flex gap-5 py-7"><MapPin className="mt-1 size-5 shrink-0 text-[#c59b27]" /><div><h3 className="font-serif text-2xl text-[#0f2942]" data-testid="contact-expectation-region-title">European business focus</h3><p className="mt-2 text-sm leading-6 text-[#64748b]" data-testid="contact-expectation-region-copy">Working arrangements, availability, and any time-zone details are agreed as part of the conversation.</p></div></div></div></div></section>
    </PageFrame>
  );
}
