import { ArrowUpRight, MoveRight } from "lucide-react";
import { Link } from "react-router-dom";
import PageFrame from "@/components/PageFrame";
import Seo from "@/components/Seo";
import { services } from "@/lib/site";

export default function Services() {
  return (
    <PageFrame>
      <Seo path="/services" title="Services | LinkedIn, Email Outreach, Business Support & AI Video | Arcturus" description="Explore Arcturus service modules: LinkedIn management, email outreach, business support, and AI video creation with transparent scope and custom quotes." />
      <section className="border-b border-[#e2dfd8]" data-testid="services-hero"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24 lg:px-10 lg:py-28"><p className="font-mono text-[10px] font-semibold uppercase tracking-[0.2em] text-[#92400e]" data-testid="services-eyebrow">The service menu</p><h1 className="mt-5 max-w-4xl font-serif text-5xl font-medium leading-[1.08] tracking-[-0.035em] text-[#0f172a] sm:text-6xl lg:text-7xl" data-testid="services-heading">Four ways to create more <span className="italic text-[#0f2942]">capacity.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#475569]" data-testid="services-intro">Each service has a clear scope, a practical process, and room to shape the detail around your business. Explore the full breakdown before you write.</p></div></section>
      <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 sm:py-28 lg:px-10" data-testid="services-catalog"><div className="grid gap-4 md:grid-cols-2">{services.map((service, index) => <Link key={service.slug} to={`/services/${service.slug}`} className="group flex min-h-[330px] flex-col justify-between border border-[#e2dfd8] bg-white p-7 transition-transform duration-200 hover:-translate-y-1 hover:border-[#c59b27] sm:p-9" data-testid={`services-overview-card-${service.slug}`}><div className="flex items-start justify-between"><span className="font-mono text-[10px] tracking-[0.18em] text-[#c59b27]" data-testid={`services-overview-number-${service.slug}`}>0{index + 1}</span><ArrowUpRight className="size-5 text-[#94a3b8] transition-colors duration-200 group-hover:text-[#0f2942]" /></div><div><p className="font-mono text-[10px] uppercase tracking-[0.16em] text-[#64748b]" data-testid={`services-overview-eyebrow-${service.slug}`}>{service.eyebrow}</p><h2 className="mt-3 font-serif text-3xl font-medium text-[#0f172a]" data-testid={`services-overview-title-${service.slug}`}>{service.title}</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#64748b]" data-testid={`services-overview-description-${service.slug}`}>{service.description}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#0f2942]">Read service details <MoveRight className="size-4 transition-transform duration-200 group-hover:translate-x-1" /></span></div></Link>)}</div></section>
      <section className="bg-[#0f2942] text-white" data-testid="services-start-section"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 sm:py-24 lg:grid-cols-[1fr_0.8fr] lg:items-end lg:px-10"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#f5d783]" data-testid="services-start-eyebrow">Where to start</p><h2 className="mt-4 max-w-2xl font-serif text-4xl font-medium leading-tight sm:text-5xl" data-testid="services-start-heading">Choose the need, not the perfect label.</h2></div><p className="max-w-md text-base leading-7 text-[#b9c5d4]" data-testid="services-start-copy">If your brief sits between services, that is useful context rather than a problem. Send an overview of what you need to move forward and we can shape the right starting point together.</p></div></section>
    </PageFrame>
  );
}
