import { ArrowUpRight, MoveRight } from "lucide-react";
import { Link } from "react-router-dom";
import PageFrame from "@/components/PageFrame";
import Seo from "@/components/Seo";
import ServiceFitGuide from "@/components/ServiceFitGuide";
import { orderedServices } from "@/lib/site";

const panelColours = ["bg-[#eef2ff]", "bg-white", "bg-[#e8f2ef]", "bg-[#ece8f4]", "bg-white", "bg-[#f1eee6]"];

export default function Services() {
  return <PageFrame><Seo path="/services" />
    <section className="relative overflow-hidden border-b border-[#ddd8cd]" data-testid="services-hero"><div className="absolute -right-20 top-10 size-72 rounded-full border border-[#765b9a]/20" aria-hidden="true" /><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-24 lg:px-10 lg:py-28"><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#4263aa]" data-testid="services-eyebrow">Six focused services</p><h1 className="mt-5 max-w-5xl break-words font-serif text-[2.4rem] leading-[1.08] text-[#0f172a] sm:text-6xl lg:text-7xl" data-testid="services-heading">B2B outreach and business support, with clear scope and pricing.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[#475569]" data-testid="services-intro">I handle each service directly and keep communication in writing. Start with one service or follow the related links when your brief needs supporting work.</p></div></section>
    <section className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20 lg:px-10" data-testid="services-fit-section"><ServiceFitGuide /></section>
    <section className="mx-auto max-w-7xl px-5 pb-20 sm:px-8 sm:pb-28 lg:px-10" data-testid="services-catalog"><div className="grid gap-5 md:grid-cols-2">{orderedServices.map((service, index) => <Link key={service.slug} to={`/services/${service.slug}`} className={`premium-panel premium-lift group flex min-h-[340px] flex-col justify-between rounded-[2rem] border border-[#ddd8cd] p-7 sm:p-9 ${panelColours[index]}`} data-testid={`services-overview-card-${service.slug}`}><div className="flex items-start justify-between"><span className="font-mono text-[10px] tracking-[0.18em] text-[#4263aa]" data-testid={`services-overview-number-${service.slug}`}>0{index + 1}</span><ArrowUpRight className="size-5 text-[#64748b] transition-[color,transform] duration-200 group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-[#0f2942]" /></div><div><p className="font-mono text-[9px] uppercase tracking-[0.16em] text-[#64748b]" data-testid={`services-overview-eyebrow-${service.slug}`}>{service.eyebrow}</p><h2 className="mt-3 break-words font-serif text-3xl text-[#0f172a]" data-testid={`services-overview-title-${service.slug}`}>{service.title}</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#64748b]" data-testid={`services-overview-description-${service.slug}`}>{service.description}</p><div className="mt-7 flex flex-col gap-4 border-t border-[#0f2942]/10 pt-5 sm:flex-row sm:items-center sm:justify-between"><span className="font-highlight text-lg text-[#0f2942]" data-testid={`services-overview-price-${service.slug}`}>{service.price}</span><span className="inline-flex items-center gap-2 text-sm font-semibold text-[#0f2942]">View service <MoveRight className="size-4 transition-transform duration-200 group-hover:translate-x-1" /></span></div></div></Link>)}</div></section>
    <section className="bg-[#0f2942] text-white" data-testid="services-start-section"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 sm:py-24 lg:grid-cols-[1fr_0.8fr] lg:items-end lg:px-10"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#9bc8c0]" data-testid="services-start-eyebrow">Where to start</p><h2 className="mt-4 max-w-2xl break-words font-serif text-4xl leading-tight text-white sm:text-5xl" data-testid="services-start-heading">Choose the need, not the perfect label.</h2></div><div><p className="max-w-md text-base leading-7 text-[#cbd5e1]" data-testid="services-start-copy">If your brief sits between services, send an overview of what you need to move forward. I will suggest the most useful starting point in writing.</p><Link to="/contact" className="mt-6 inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 text-sm font-semibold text-[#0f2942] transition-[background-color,transform] duration-200 hover:-translate-y-0.5 hover:bg-[#dce6ff]" data-testid="services-contact-link">Contact me <ArrowUpRight className="size-4" /></Link></div></div></section>
  </PageFrame>;
}
